# -*- coding: utf-8 -*-
"""計算思維 期末報告 模型測試.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pje-XPY-8YbPodPMuzeOJ2-YKP9JHqOx
"""

!pip install datasets
!pip install scikit-learn
!pip install -U transformers --upgrade --force-reinstall
!pip install pandas

from transformers import BertTokenizer, BertForSequenceClassification, Trainer, TrainingArguments
from sklearn.model_selection import train_test_split
from datasets import Dataset
import pandas as pd
import os
os.environ["WANDB_DISABLED"] = "true"

# 讀取資料集
df = pd.read_csv("final_fraud_and_normal_messages_1000.csv")

# 拆分訓練集與測試集
train_df, test_df = train_test_split(df, test_size=0.2, stratify=df["是否詐騙"])

# 轉換為 Hugging Face 的 Dataset 格式
train_dataset = Dataset.from_pandas(train_df.reset_index(drop=True))
test_dataset = Dataset.from_pandas(test_df.reset_index(drop=True))


# 載入 BERT 分詞器
tokenizer = BertTokenizer.from_pretrained("bert-base-chinese")

def tokenize(example):
    return tokenizer(example["留言內容"], padding="max_length", truncation=True)

train_dataset = train_dataset.map(tokenize, batched=True)
test_dataset = test_dataset.map(tokenize, batched=True)
train_dataset = train_dataset.rename_column("是否詐騙", "label")
test_dataset = test_dataset.rename_column("是否詐騙", "label")
# 載入 BERT 模型（分類用）
model = BertForSequenceClassification.from_pretrained("bert-base-chinese", num_labels=2)

# 設定訓練參數
training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    # Changed evaluation_strategy to eval_strategy
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_dir="./logs",
    # Add remove_unused_columns=False to prevent issues with extra columns
    remove_unused_columns=False
)

from sklearn.metrics import accuracy_score

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = logits.argmax(axis=-1)
    acc = accuracy_score(labels, predictions)
    return {"accuracy": acc}

# 建立 Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics,
)

# 開始訓練
trainer.train()
trainer.save_model("./results")

# 壓縮整個模型資料夾
!zip -r bert_trained_model.zip ./results

# 下載 zip 檔
from google.colab import files
files.download("bert_trained_model.zip")

trainer.save_model("./results")

from transformers import BertTokenizer, BertForSequenceClassification
import torch

# 載入剛剛訓練好的模型與分詞器
model = BertForSequenceClassification.from_pretrained("./results")
tokenizer = BertTokenizer.from_pretrained("bert-base-chinese")

# 預測函式
def predict(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True)
    with torch.no_grad():
        outputs = model(**inputs)
    probs = torch.nn.functional.softmax(outputs.logits, dim=-1)
    label = torch.argmax(probs).item()
    confidence = probs[0][label].item()
    return "詐騙留言" if label == 1 else "正常留言", confidence

text = "出售iPad Mini，先匯款，面交"
result, score = predict(text)
print(f"結果：{result}（信心分數：{score:.2f}）")

text = "出售iPad Mini，先匯款保留，可於台北面交，私訊聊"
result, score = predict(text)
print(f"結果：{result}（信心分數：{score:.2f}）")

text = "出售iPad Mini，含面交時付款"
result, score = predict(text)
print(f"結果：{result}（信心分數：{score:.2f}）")



# 準確度
from sklearn.metrics import accuracy_score

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = logits.argmax(axis=-1)
    acc = accuracy_score(labels, predictions)
    return {"accuracy": acc}

trainer.evaluate()

results = trainer.evaluate()
print(f"模型準確率：{results['eval_accuracy']:.4f}")



"""※ 如何在自己的電腦上使用🤔：

"""

# Step 1：掛載 Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Step 2：複製 zip 檔到 Colab 並解壓縮
!cp "/content/drive/MyDrive/計算思維與人工智慧期末/bert_trained_model.zip" . #此處要改成zip在你雲端的上傳位置
!unzip bert_trained_model.zip -d ./results

# Step 3：安裝套件（只需執行一次）
!pip install -U transformers
!pip install torch

# Step 4：載入模型並定義預測函式
from transformers import BertTokenizer, BertForSequenceClassification
import torch

# 載入模型與分詞器
model = BertForSequenceClassification.from_pretrained("./results/results/checkpoint-300")
tokenizer = BertTokenizer.from_pretrained("bert-base-chinese")

# 預測函式
def predict(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True)
    with torch.no_grad():
        outputs = model(**inputs)
    probs = torch.nn.functional.softmax(outputs.logits, dim=-1)
    label = torch.argmax(probs).item()
    confidence = probs[0][label].item()
    return "詐騙留言" if label == 1 else "正常留言", confidence

# Step 5：輸入你要測試的留言
text = "出售PS5主機"
result, score = predict(text)
print(f"判斷結果：{result}（信心分數：{score:.2f}）")